#!/usr/bin/env python3
"""Aggregate experiment runs across models, and write the index.

Two outputs:

  storage/generated/<scenario>/<condition>/summary.json   mean +/- sd per mode, over runs
  storage/RUNS.md                                         one row per condition, all scenarios

AGGREGATION COMES FIRST, COMPARISON SECOND, and that ordering is the point. The `llm` adapter arm's
flow recall spans 0.33-0.87 across three runs of the SAME model, so a table of one run per model
would present sampling noise as a model difference. Everything here reports mean and spread over
runs within a condition; nothing compares a single run to a single run.

A condition with n=1 is reported with sd of "-" rather than 0.00. Zero spread and unknown spread
are different claims, and printing 0.00 for a single sample asserts the stronger one.

Run: PYTHONPATH=. python3 scripts/summarize_runs.py [--scenario kidstube] [--write]
"""
from __future__ import annotations
import argparse
import json
import re
import statistics
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import config
import runs

# The eval report is plain text; these pull the two lines every comparison actually uses.
ALL_ROW = re.compile(r"^ALL\s+(\d+)\s+(\d+)\s+(\d+)\s+([\d.]+)\s+([\d.]+)\s+([\d.]+)", re.M)
CITATION = re.compile(r"^\s+all_valid_rate\s+([\d.]+)", re.M)
N_GEN = re.compile(r"n_generated=(\d+)")


def parse_eval(text: str) -> dict | None:
    m = ALL_ROW.search(text)
    if not m:
        return None
    tp, fp, fn, p, r, f1 = m.groups()
    cit = CITATION.search(text)
    n = N_GEN.search(text)
    return {"tp": int(tp), "fp": int(fp), "fn": int(fn),
            "precision": float(p), "recall": float(r), "f1": float(f1),
            "citation_all_valid": float(cit.group(1)) if cit else None,
            "n_generated": int(n.group(1)) if n else None}


def _stat(values: list[float]) -> dict:
    vals = [v for v in values if v is not None]
    if not vals:
        return {"n": 0, "mean": None, "sd": None}
    return {"n": len(vals), "mean": round(statistics.fmean(vals), 4),
            "sd": round(statistics.stdev(vals), 4) if len(vals) > 1 else None}


def collect(scenario: str | None = None) -> dict:
    """{scenario: {condition: {mode: [per-run dicts]}}} plus each run's DFD metadata."""
    out: dict = {}
    for scen, cond, run, run_dir in runs.iter_runs(scenario):
        entry = out.setdefault(scen, {}).setdefault(cond, {"modes": {}, "runs": {}})
        dfd_path = run_dir / "dfd.json"
        if dfd_path.exists():
            meta = json.loads(dfd_path.read_text()).get("_meta", {})
            entry["runs"][run] = {
                "model": meta.get("model") or meta.get("derived_from", {}).get("model", "?"),
                "backend": meta.get("backend") or meta.get("derived_from", {}).get("backend", "?"),
                "n_elements": len(json.loads(dfd_path.read_text()).get("elements", [])),
                "n_flows": len(json.loads(dfd_path.read_text()).get("flows", [])),
            }
        gen_dir = runs.generated_dir(scen, cond, run)
        if not gen_dir.exists():
            continue
        for report in sorted(gen_dir.glob("*_eval.txt")):
            mode = report.name[: -len("_eval.txt")]
            parsed = parse_eval(report.read_text())
            if parsed:
                parsed["run"] = run
                entry["modes"].setdefault(mode, []).append(parsed)
    return out


def summarize(entry: dict) -> dict:
    return {mode: {k: _stat([r[k] for r in rows])
                   for k in ("precision", "recall", "f1", "citation_all_valid", "n_generated")}
            for mode, rows in entry["modes"].items()}


def _fmt(s: dict) -> str:
    if s["mean"] is None:
        return "-"
    return f"{s['mean']:.2f} ± {s['sd']:.2f}" if s["sd"] is not None else f"{s['mean']:.2f} (n=1)"


def render_index(data: dict) -> str:
    lines = ["# Experiment runs",
             "",
             "Generated by `scripts/summarize_runs.py` -- do not edit by hand.",
             "",
             "Each row aggregates over the runs in one condition. `n=1` marks a point estimate: "
             "the `llm` arm's flow recall spans 0.33-0.87 across runs of one model, so a single "
             "run is not a comparison.",
             ""]
    for scen in sorted(data):
        lines += [f"## {scen}", "",
                  "| condition | input | arm | model | mode | runs | precision | recall | F1 | citation |",
                  "|---|---|---|---|---|---:|---|---|---|---|"]
        for cond in sorted(data[scen]):
            entry = data[scen][cond]
            try:
                parts = runs.parse_condition(cond)
            except ValueError:
                parts = {"input": "?", "arm": "?", "model": "?"}
            summ = summarize(entry)
            for mode in sorted(summ):
                s = summ[mode]
                lines.append(
                    f"| `{cond}` | {parts['input']} | {parts['arm']} | {parts['model']} | {mode} "
                    f"| {s['recall']['n']} | {_fmt(s['precision'])} | {_fmt(s['recall'])} "
                    f"| {_fmt(s['f1'])} | {_fmt(s['citation_all_valid'])} |")
            if not summ:
                lines.append(f"| `{cond}` | {parts['input']} | {parts['arm']} | {parts['model']} "
                             f"| (no eval yet) | {len(entry['runs'])} | - | - | - | - |")
        lines.append("")

    legacy = sorted(p.name for p in runs.DERIVED_ROOT.glob("*.json"))
    if legacy:
        lines += ["## Grandfathered (pre-Week-12 layout)", "",
                  "Flat files with no condition key. Left in place because committed reports cite "
                  "these paths; not aggregated here.", ""]
        lines += [f"- `storage/derived/{n}`" for n in legacy]
        lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--scenario", default=None)
    ap.add_argument("--write", action="store_true",
                    help="Write summary.json per condition and storage/RUNS.md.")
    args = ap.parse_args()

    data = collect(args.scenario)
    index = render_index(data)
    print(index)

    if args.write:
        for scen in data:
            for cond, entry in data[scen].items():
                path = runs.summary_path(scen, cond)
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(json.dumps(
                    {"scenario": scen, "condition": cond, **runs.parse_condition(cond),
                     "runs": entry["runs"], "by_mode": summarize(entry)}, indent=2) + "\n")
        out = config.ROOT / "storage" / "RUNS.md"
        out.write_text(index)
        print(f"\n(wrote {out} and per-condition summary.json)", file=sys.stderr)


if __name__ == "__main__":
    main()
